name: Erc4626
description: Token Vault Indexer
networks:
  - id: 137
    start_block: 0
    contracts:
      - name: ERC4626
        abi_file_path: abis/erc4626-abi.json
        address: "0x4A7CfE3ccE6E88479206Fefd7b4dcD738971e723" # ERC4626-Wrapped Aave v2 DAI (wa2-DAI)
        handler: ./src/EventHandlers.js
        events:
          - event: "Deposit"
            requiredEntities:
              - name: "TokenVault"
          - event: "Withdraw"
            requiredEntities:
              - name: "TokenVault"